### ISSUE TITLE
Laravel GoTo Controller not working for laravel v8 and above

### ISSUE THREAD

**Issue by RakeshPatelNexios** [erlangp/goto-route-controller-laravel#2]
Laravel GoTo controller is not working for the laravel versions v8 or above.

As we know the route syntax has been changed in laravel since v8. So we have the below syntax for route:

**Route::get('orders/index', [App\Http\Controllers\OrderController::class,'index'])->name('orders.index');**

I like your plugin but please kindly add this support for laravel v8 and above

**Comment by erlangparasu** [comment]
Thanks for using this extension & thanks for asking the feature. I will get it to work ASAP :)

**Comment by erlangparasu** [comment]
@RakeshPatelNexios Hi.. Support for Laravel 8.x + just released (v2.2.0) :)

**Comment by RakeshPatelNexios** [comment]
Most Welcome ErlangParasu

**Comment by RakeshPatelNexios** [comment]
Wow, that's good

thanks bro

**Comment by RakeshPatelNexios** [comment]
Hi ErlangParasu,

It's done.

Thankyou for all the efforts you have placed for this release.

I'm really happy to use this extension.

Thank you so much once again
